- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: system
  types: [rust]
  pass_filenames: false
  stages: [commit]
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false
  stages: [commit]
- id: build
  name: build
  description: Build the package.
  entry: cargo build
  language: system
  types: [rust]
  pass_filenames: false
  stages: [push]
- id: no-warnings
  name: no-warnings
  description: Build the package and error on warnings.
  entry: cargo rustc -- -D warnings
  language: system
  types: [rust]
  pass_filenames: false
  stages: [push]
- id: clippy
  name: clippy
  description: Lint rust source files.
  entry: cargo clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
  stages: [commit]
- id: test
  name: test
  description: Run tests with cargo test.
  entry: cargo test
  language: system
  types: [rust]
  pass_filenames: false
  stages: [push]
- id: audit
  name: audit
  description: Audit dependencies for security vulnerabilities with cargo audit. Requires cargo-audit to be installed.
  entry: cargo audit
  language: system
  types: [rust]
  pass_filenames: false
  stages: [push]
